/* SELECT OP DE WAREHOUSE */
SELECT TOP (1000) [RideId]
      ,[StartPoint]
      ,[EndPoint]
      ,(cast([StartPoint] as geometry)).STDistance(cast([EndPoint] as geometry)) 'distance'
      ,[StartTime]
      ,[EndTime]
      ,[Duurtijd]
      ,[ClientName]
      ,[ClientEmail]
      ,[ClientStreet]
      ,[ClientNumber]
      ,[ClientZipcode]
      ,[ClientCity]
      ,[ClientCountryCode]
      ,[ClientSubValidFrom]
      ,[ClientSubDesc]
      ,[StartLockType]
      ,[StartLockStreet]
      ,[StartLockNumber]
      ,[StartLockZipcode]
      ,[StartLockDistrict]
      ,[EndLockType]
      ,[EndLockStreet]
      ,[EndLockNumber]
      ,[EndLockZipCode]
      ,[EndLockDistrict]
      ,[Date]
      ,[DayOfMonth]
      ,[Month]
      ,[Year]
      ,[DayOfWeek]
      ,[DayOfYear]
      ,[Weekday]
      ,[MonthName]
      ,[weer]
  FROM [velo_dwh].[dbo].[factRide]
